(function(){"use strict";var f=function(a,b,c){var d;c?(d=document.createEvent("CustomEvent"),d.initCustomEvent(a,!0,!0,c)):(d=document.createEvent("Event"),d.initEvent(a,!0,!0));b.dispatchEvent(d);return d};var g=["auto","none","pan-x","pan-y"],h=2,l=null,m=!1,n=null,p=null,r=function(a,b){b.preventDefault();var c=b.changedTouches[0];null==l&&(l=c.identifier,n=c.clientX,p=c.clientY,m=!1);q(a,"pointerover",b);q(a,"pointerdown",b)},s=function(a,b,c){if(!m){var d;if(d=1!=a&&null!=n){var e=c.touches[0];d=Math.abs(e.clientX-n);e=Math.abs(e.clientY-p);d=2==a?d>e:e>d}d?(q(b,"pointercancel",c),m=!0,l=null):(q(b,"pointermove",c),c.preventDefault());p=n=null}},u=function(a,b){m||(t(b),q(a,"pointerup",b),q(a,"pointerout",
b))},t=function(a){l&&v(a,function(a){l==a.identifier&&(p=n=l=null)})},w=function(a,b,c,d){var e=document.createEvent("Event");e.initEvent(a,!0,!0);e.clientX=c.clientX;e.clientY=c.clientY;e.pointerId=b;e.isPrimary=d;return e},x={},y=function(a){a=""+a.identifier;x[a]||(x[a]=h++);return x[a]},z=function(a,b,c){c.preventDefault();a.dispatchEvent(w(b,1,c,!0))},A=function(a,b,c){a.dispatchEvent(w(b,c.pointerId,c,c.isPrimary))},q=function(a,b,c){v(c,function(c){a.dispatchEvent(w(b,y(c),c,l==c.identifier))})},
v=function(a,b){for(var c=a.changedTouches,d=0,e=c.length;d<e;++d)b(c[d])};var B=function(a){var b=document.createEvent("Event");b.initEvent("tap",!0,!0);b.clientX=a.clientX;b.clientY=a.clientY;return b},C=function(a,b,c,d,e){var k=document.createEvent("Event");k.initEvent(a,!0,!0);k.dx=b;k.dy=c;k.ddx=d;k.ddy=e;return k};document.registerElement&&document.registerElement("gwd-gesture",{prototype:Object.create(HTMLElement.prototype,{createdCallback:{value:function(){this.a={};this.b=!1;this.l=f.bind(null,"hover",this);this.i=this.down_.bind(this);this.j=this.move_.bind(this);this.m=this.up_.bind(this);this.k=this.out_.bind(this);this.h=this.cancel_.bind(this);var a=1;switch(this.getAttribute("touch-action")){case "auto":a=0;break;case "pan-x":a=2;break;case "pan-y":a=3}var a=a||0,b=g[a];this.setAttribute("touch-action",
b);this.style.touchAction=b;this.style.msTouchAction=b;navigator.pointerEnabled||(navigator.msPointerEnabled?(this.addEventListener("MSPointerOver",A.bind(null,this,"pointerover"),!1),this.addEventListener("MSPointerDown",A.bind(null,this,"pointerdown"),!1),this.addEventListener("MSPointerMove",A.bind(null,this,"pointermove"),!1),this.addEventListener("MSPointerUp",A.bind(null,this,"pointerup"),!1),this.addEventListener("MSPointerOut",A.bind(null,this,"pointerout"),!1),this.addEventListener("MSPointerCancel",
A.bind(null,this,"pointercancel"),!1)):(this.addEventListener("mouseover",z.bind(null,this,"pointerover"),!1),this.addEventListener("mousedown",z.bind(null,this,"pointerdown"),!1),this.addEventListener("mousemove",z.bind(null,this,"pointermove"),!1),this.addEventListener("mouseup",z.bind(null,this,"pointerup"),!1),this.addEventListener("mouseout",z.bind(null,this,"pointerout"),!1),void 0!==window.ontouchstart&&(this.addEventListener("touchstart",r.bind(null,this),!1),0!=a&&this.addEventListener("touchmove",
s.bind(null,a,this),!1),this.addEventListener("touchend",u.bind(null,this),!1))))},enumerable:!0},attachedCallback:{value:function(){this.addEventListener("pointerover",this.l,!1);this.addEventListener("pointerdown",this.i,!1);this.addEventListener("pointermove",this.j,!1);this.addEventListener("pointerup",this.m,!1);this.addEventListener("pointerout",this.k,!1);this.addEventListener("pointercancel",this.h,!1)},enumerable:!0},detachedCallback:{value:function(){this.removeEventListener("pointerover",
this.l,!1);this.removeEventListener("pointerdown",this.i,!1);this.removeEventListener("pointermove",this.j,!1);this.removeEventListener("pointerup",this.m,!1);this.removeEventListener("pointerout",this.k,!1);this.removeEventListener("pointercancel",this.h,!1)},enumerable:!0},down_:{value:function(a){a.isPrimary&&(this.addPointer_(a),this.b=!1)},enumerable:!1},move_:{value:function(a){var b=this.a[""+a.pointerId];if(b){if(10<Math.abs(b.c-a.clientX)||10<Math.abs(b.d-a.clientY))this.b=!0;b.g||(this.dispatchEvent(C("trackstart",
0,0,0,0)),b.g=!0);this.dispatchEvent(C("track",a.clientX-b.c,a.clientY-b.d,a.clientX-b.e,a.clientY-b.f));b.e=a.clientX;b.f=a.clientY}},enumerable:!1},up_:{value:function(a){this.upOut_(a)&&(this.b||this.dispatchEvent(B(a)))},enumerable:!1},out_:{value:function(a){this.upOut_(a);f("hoverend",this)},enumerable:!1},upOut_:{value:function(a){var b=this.a[""+a.pointerId];b&&(b.g&&this.dispatchEvent(C("trackend",a.clientX-b.c,a.clientY-b.d,a.clientX-b.e,a.clientY-b.f)),this.removePointer_(a));return b},
enumerable:!1},cancel_:{value:function(a){this.removePointer_(a);this.b=!0},enumerable:!1},removePointer_:{value:function(a){a=""+a.pointerId;this.a[a]&&delete this.a[a]},enumerable:!1},addPointer_:{value:function(a){var b=""+a.pointerId;this.a[b]||(this.a[b]={c:a.clientX,d:a.clientY,e:a.clientX,f:a.clientY,g:!1})},enumerable:!1}})});})()
